### ISSUE TITLE
Codespaces - cannot install the extension

### ISSUE THREAD

**Issue by sandy081** [misolori/vscode-fluent-icons#11]
It seems this extensions is tagged as strict ui kind and hence it cannot be installed in web.

```
"extensionKind": [
		"ui"
]
```

Please change it to 

```
"extensionKind": [
		"ui",
                "workspace"
]
```

or remove the entry completely so that VS Code can infer it smartly.

**Comment by misolori** [comment]
I actually already set this:

https://github.com/misolori/vscode-fluent-icons/blob/b70187d287d60b3e217e10f59d6abc1e5f79f474/package.json#L20-L22

Is there a reason why it's not picked up by the web?

**Comment by sandy081** [comment]
It seems the extension was not published with the change - I see that latest version (that got published one hour ago from this time) has the change and can be installed in codespaces. 

So feel free to close this.

**Comment by misolori** [comment]
Ah, I think I must've forgot to rebuild when I added that. Thanks!
