### ISSUE TITLE
Update icons gitlens

### ISSUE THREAD

**Issue by natuan62** [misolori/vscode-fluent-icons#14]
- Icon gitlens still default icon of vscode, can you update 5 icons ?
```
- gitlens repository
- gitlens commit
- gitlens file history
- gitlens line history
- gitlens stashes
```
![image](https://user-images.githubusercontent.com/10808157/112420380-b00d4000-8d5f-11eb-88b2-fe81e5ae968b.png)

**Comment by misolori** [comment]
I can only update product icons, icons that are added by an extension are not themeable unless they're using product icons. In the GitLens case these are custom svg so they are not themeable, sorry about that.
