### ISSUE TITLE
Icons not displayed properly in IntelliSense

### ISSUE THREAD

**Issue by davidmszrs** [misolori/vscode-fluent-icons#15]
The property and method / function icons displayed in IntelliSense are the ones from the standard product theme, but not every time. It seems to occur only when I go 1 level deep on a chain (eg. obj.prop1), one more level and it breaks (eg. obj.prop1.prop2), sometimes it's not even one level - awkward, I know. I may be reading too much into it or maybe I'm missing something? Is it supposed to work like that?

**Expected behavior**
New product icons show up everywhere in IntelliSense.

**Screenshots**
![image](https://user-images.githubusercontent.com/18365917/116240847-f7c32500-a76c-11eb-9625-4c62926fbbbe.png)
![image](https://user-images.githubusercontent.com/18365917/116240887-04e01400-a76d-11eb-9d67-ab6862ba9bd4.png)

Also, I have not seen any new icon replacing the blue property icon. It always shows up like this. 
![image](https://user-images.githubusercontent.com/18365917/116241116-3a84fd00-a76d-11eb-9f8b-7856dfc5ebb6.png)

Is there no new icon or is it a bug?

Great theme btw, man. 🎉

**Comment by misolori** [comment]
Ah, there must be other symbols that are using the same icon that I missed. I can fix that. 

And right now it's only those two icons, I haven't gotten around to adding the rest but that's coming soon. Thanks for the feedback!

**Comment by davidmszrs** [comment]
Any update on this? I can have a look at the missing mappings and make a PR if you'd like.

**Comment by misolori** [comment]
Finally got around to adding these icons:

![image](https://user-images.githubusercontent.com/35271042/117528069-3040db00-af85-11eb-91ee-31f02fc5c9be.png)

**Comment by davidmszrs** [comment]
Looks awesome! Great work!
