### ISSUE TITLE
Azure Data Studio update Connections icon

### ISSUE THREAD

**Issue by Code-DJ** [misolori/vscode-fluent-icons#16]
Can you please update the Connections icon for ADS? I don't use Notebooks but looks like that icon also needs an update.

Azure Data Studio is based on VS Code, so I was able to copy the extension from .vscode to .azuredatastudio.

Be sure to use latest ADS 1.29.0 which was released today. Fluent Icons don't work on previous versions as it is based on older VS Code.

<img width="49" alt="image" src="https://user-images.githubusercontent.com/8212554/118896911-ee8e2980-b8ce-11eb-9d1b-84d87d6be317.png">

**Comment by misolori** [comment]
Unfortunately those icons are not using Codicons, the built-in icon library for VS Code, so I can't replace those. They'll need to update their icons in order to support this.

**Comment by Code-DJ** [comment]
Hi, @misolori FYI, I opened an issue on ADS https://github.com/microsoft/azuredatastudio/issues/15530. It is assigned to Next (June) Milestone. Thanks!
