### ISSUE TITLE
Doesn't work in codespaces

### ISSUE THREAD

**Issue by Milo123459** [misolori/vscode-fluent-icons#18]
**Describe the bug**
It doesn't work in codespaces
**Expected behavior**
Should show the fluent icons
**Screenshots**
![image](https://user-images.githubusercontent.com/50248166/131181087-f6ab9eb1-8b2d-4928-90ac-e2397589a770.png)

**Additional context**

**Comment by Milo123459** [comment]
@misolori do you know of a fix?

**Comment by misolori** [comment]
This is a known issue on the VS Code side where all product icon fonts fail to load. Closing as this is an upstream issue and will be fixed when VS Code addresses this.

**Comment by Milo123459** [comment]
Can you link the tracking issue on the vscode repo?

**Comment by misolori** [comment]
https://github.com/microsoft/vscode/issues/131248

**Comment by mukundshah** [comment]
What about a temporary fix: Install the `pi-fluent-icons.ttf` locally. 
The browser should detect that, right?
It works for other fonts, will it work for this?

PS: I tried this, but the font on this repo is `fluent-icons.ttf` and we need `pi-fluent-icons.ttf`.

**Comment by misolori** [comment]
This is now fixed in github.dev:

<img width="1140" alt="CleanShot 2021-09-10 at 08 40 02@2x" src="https://user-images.githubusercontent.com/35271042/132880555-21e2a169-e097-4a1e-8cd0-94c1c1d995fb.png">
