### ISSUE TITLE
The pug folder has no icon

### ISSUE THREAD

**Issue by SineYlo** [misolori/vscode-fluent-icons#20]
Why doesn't the PUG folder have an icon?
Is that what you intended?
Pug files just have an icon
![PUG](https://i.ibb.co/qMYLj4p/Ashampoo-Snap-2-2021-20h19m51s-001-desc-pug-Visual-Studio-Code.jpg)

**Comment by misolori** [comment]
The Fluent theme is a product icon theme and what you are referring to is a file icon theme, which is not supported in this theme. You likely want to file that issue with your file icon theme, which looks like the [Material Icon Theme](https://github.com/PKief/vscode-material-icon-theme/issues).
