### ISSUE TITLE
Feature request: Icon for copilot

### ISSUE THREAD

**Issue by Milo123459** [misolori/vscode-fluent-icons#21]
<img width="40" alt="image" src="https://user-images.githubusercontent.com/50248166/144467551-d102c264-e00b-4f90-863d-4b5be9737f4e.png">

That's the current icon, and it doesn't really fit in with Fluent Icons.

**Comment by Milo123459** [comment]
*Only available on Github copilot nightly ATM

**Comment by misolori** [comment]
I could use the robot icon for this:

<img width="149" alt="CleanShot 2021-12-02 at 11 39 53@2x" src="https://user-images.githubusercontent.com/35271042/144491427-f992fd74-9bfe-43ee-b504-bd1d3c152b28.png">

**Comment by Milo123459** [comment]
I like that. Possibly a plane, or a pilot?

**Comment by misolori** [comment]
There isn't a pilot but there is a plane:

<img width="120" alt="CleanShot 2021-12-02 at 11 45 28@2x" src="https://user-images.githubusercontent.com/35271042/144492129-32c14ad8-25d7-4d46-a049-cb59e7b21786.png">

I think the bot might work best though since it is ai-based

**Comment by misolori** [comment]
<img width="323" alt="CleanShot 2021-12-02 at 11 52 09@2x" src="https://user-images.githubusercontent.com/35271042/144493003-4881f7af-aa8d-4689-a447-75c69b0189ef.png">

**Comment by Milo123459** [comment]
The robot looks really good.

Just re-iterating, this needs to effect github copilot nightly and github copilot.

**Comment by misolori** [comment]
This will work on any version that they use, since they are contributing a product icon theme I can easily replace it regardless of the version.

**Comment by misolori** [comment]
Will push this shortly to the marketplace, thanks for the suggestion!

![image](https://user-images.githubusercontent.com/35271042/144494268-bec0d06b-3823-40c3-9c08-bcdb40e77f22.png)

**Comment by Milo123459** [comment]
@misolori 
<img width="51" alt="image" src="https://user-images.githubusercontent.com/50248166/144501166-a8e1ad34-1007-4608-afdb-0ac37b85780f.png">
Icon in the status bar changed, but the one in the side bar didn't...

**Comment by misolori** [comment]
The activity bar is using an SVG and not a product icon. I will ask to see if they can switch to it.

**Comment by Milo123459** [comment]
Oh right, thanks

**Comment by misolori** [comment]
Looks like it's possible and an easy 1 line change, will see if the team can adopt this:

<img width="96" alt="CleanShot 2021-12-02 at 13 14 50@2x" src="https://user-images.githubusercontent.com/35271042/144504191-edd8edfb-2140-492b-9858-af56790b97c7.png">

**Comment by Milo123459** [comment]
Any updates?

**Comment by misolori** [comment]
They said they will look into updating it so hopefully we'll see it soon

**Comment by Milo123459** [comment]
<img width="17" alt="image" src="https://user-images.githubusercontent.com/50248166/161141413-6a2883e1-dcc1-4956-87a8-aa02ebc273f2.png">
They started using it here?
