### ISSUE TITLE
Request: Add Docker and Git lens icon

### ISSUE THREAD

**Issue by emigdio821** [misolori/vscode-fluent-icons#26]
Hi there! this is not a bug but a request.

Is it possible to add icons for Docker and/or Git lens? 
Thanks in advance. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6751108/173969323-879e7971-9a11-4f5c-b2fc-f22870f486fb.png)

**Comment by misolori** [comment]
Unfortunately, those are not using the icon library in VS Code and are using custom icons that I can't replace with the UI
