### ISSUE TITLE
Wrong Icon Showing up

### ISSUE THREAD

**Issue by Satwik29** [misolori/vscode-fluent-icons#4]
Here is the screenshot: 
![image](https://user-images.githubusercontent.com/77983013/107216055-32e96e00-6a32-11eb-970e-eb5e6707f5f9.png)

The split-screen icon appears to be different than what is in the .md file. Please look into this

**Comment by misolori** [comment]
Fixed via https://github.com/misolori/vscode-fluent-icons/commit/b71cd254d5eb4cb2f5d67388cabf83731cda5b50
