### ISSUE TITLE
Icon Request: Live share

### ISSUE THREAD

**Issue by NathanHannon** [misolori/vscode-fluent-icons#6]
I was wondering if we could have an icon for the Live Share extension.

**Comment by misolori** [comment]
@NathanHannon accidental closed? started working on this one

**Comment by NathanHannon** [comment]
> @NathanHannon accidentally closed? started working on this one

Yeah it was. I saw on the link to the product icons doc that it was up to the maintainer. I had a brain fart and forgot Microsoft also made that extension

**Comment by misolori** [comment]
No worries I'll re-open and add it to the theme
