### ISSUE TITLE
Theme of the preview

### ISSUE THREAD

**Issue by danieloprado** [misolori/vscode-fluent-icons#7]
Which theme are you using on the preview? Thanks!!!

![image](https://user-images.githubusercontent.com/7683575/107431595-6ea13800-6b05-11eb-944b-135ea3274e23.png)

**Comment by misolori** [comment]
@danieloprado that's the [GitHub Light theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme)

**Comment by sowizz** [comment]
Hi @misolori, 

what font and zsh theme are you using in current preview? Are there any customizations made to the sidebar. Looks like custom font with increased size is set.

**Comment by misolori** [comment]
Font is `Input Mono` and zsh theme is `robbyrussell`

**Comment by AurevoirXavier** [comment]
Hi! What's your file icon theme?

That looks pretty concise!

**Comment by misolori** [comment]
File icon theme is the default, Seti.

**Comment by harpreetsb** [comment]
came here to check this only 😄
